version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - violetagg
  target-branch: "0.2.x"
  labels:
  - type/dependency-upgrade
  ignore:
  # Don't update Reactor projects
  - dependency-name: io.projectreactor:*
  - dependency-name: io.projectreactor.addons:*
  rebase-strategy: disabled
- package-ecosystem: github-actions
  directory: "/"
  schedule:
      interval: daily
  open-pull-requests-limit: 10
  assignees:
      - violetagg
  target-branch: "0.2.x"
  labels:
      - type/dependency-upgrade
  rebase-strategy: disabled
